#!/bin/bash
#
# Rewrite the random_file.Bash shell script in Listing 11-16 but this time use the
# /dev/urandom character special file to create all the random numbers. Is there a
# difference in execution time? Explain any differences observed.
#
# Initial notes by learner: no need for load_default_keyboard function or character arrays
#
# SCRIPT: random_file.bash
# AUTHOR: Randy Michael
# DATE: 8/3/2007
# REV: 1.0
# PLATFORM: Not Platform Dependent
#
# PURPOSE: This script is used to create a specific size file of random 
# characters. The methods used in this script include loading an array 
# with alphanumeric characters, then using the /dev/random character 
# special file to seed the RANDOM shell variable, which in turn is 
# used to extract a random set of characters from the KEYS array to 
# build the OUTFILE of a specified MB size.
#
##########################################
# DEFINE FILES AND VARIABLES HERE
##########################################
typeset -i MB_SIZE=$1
WORKDIR=/scripts
OUTFILE=${WORKDIR}/largefile.random.txt
>$OUTFILE
THIS_SCRIPT=$(basename $0)

##########################################
# DEFINE FUNCTIONS HERE
##########################################

elapsed_time ()
{
    SEC=$1
    (( SEC < 60 )) && echo -e "[Elapsed time: $SEC seconds]\c"
    (( SEC >= 60 && SEC < 3600 )) && echo -e "[Elapsed time: $(( SEC / 60 )) min $(( SEC % 60 )) sec]\c"
    (( SEC > 3600 )) && echo -e "[Elapsed time: $(( SEC / 3600 )) hr $(( (SEC % 3600) / 60 )) min $(( (SEC % 3600) % 60 )) sec]\c"
}

usage ()
{
    echo -e "\nUSAGE: $THIS_SCRIPT Mb_size"
    echo -e "Where Mb_size is the size of the file to build\n"
}

##########################################
# BEGINNING OF MAIN
##########################################

if (( $# != 1 ))
then
    usage
    exit 1
fi

case $MB_SIZE in
    [0-9]*) : 
    ;;
    *) usage
       exit 1
    ;;
esac

echo "Building a $MB_SIZE MB random character file ==> $OUTFILE"
echo "Please be patient, this may take some time to complete..."
echo -e "Executing: .\c"

# Reset the shell SECONDS variable to zero seconds.
SECONDS=0

# Implementation using /dev/urandom stream directly
# This bypasses the shell loop and array overhead to fulfill the performance comparison
head -c $(( MB_SIZE * 4000000 )) /dev/urandom | tr -dc 'A-Za-z0-9' | head -c $(( MB_SIZE * 1048576 )) > $OUTFILE

# Capture the total seconds
TOT_SEC=$SECONDS

echo -e "\n\nSUCCESS: $OUTFILE created at $MB_SIZE MB\n"
elapsed_time $TOT_SEC

# Calculate the bytes/second file creation rate
if (( TOT_SEC > 0 ))
then
    (( MB_SEC = ( MB_SIZE * 1024000 ) / TOT_SEC ))
    echo -e "\n\nFile Creation Rate: $MB_SEC bytes/second\n"
else
    echo -e "\n\nFile Creation Rate: Fast enough to be unmeasured\n"
fi

echo -e "File size:\n"
ls -l $OUTFILE
echo

##########################################
# END OF random_file.bash SCRIPT
##########################################
